spring:
  application:
    name: taobao-registry
server:
  port: 10000

eureka:
  server:
    eviction-interval-timer-in-ms: 5000 # 扫描失效服务间隔时间
    enable-self-preservation: true  # 自我保护 85%服务无心跳时 可能是服务中心宕机这时会将服务保护起来
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false