spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      password: 123
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 915540781@qq.com #发送邮件的邮箱地址
    password:  tyuevckltvfvbcea #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 915540781@qq.com # 发送邮件的地址，和上面username一致
    # 可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
