spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    user:
      name: yhq
      password: $2a$10$bZzH0e0cAG97Zj2fmZEWGujLMPfjPIdkcxawyq87YFtkqLT8j3.n2

  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 915540781@qq.com #发送邮件的邮箱地址
    password: tyuevckltvfvbcea #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 915540781@qq.com # 发送邮件的地址，和上面username一致
    # 可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  datasource:
    hikari:
      username: root
      password: 915540781
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.18.0.3:3306/cangku?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://172.18.0.3:3306/cangku?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false


server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 172.17.150.85:22122