spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    user:
      name: yhq
      password: yhq915540781
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates/

server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 172.17.150.85:22122

