spring:
  application:
    name: item-service
  datasource:
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
  redis:
    host: 123.56.106.111
    port: 39222
#  rabbitmq:
#      host: 192.168.0.106
#      port: 5672
#      username: user
#      password: 123
#      virtual-host: /vhost_yhq
#      listener:
#        direct:
#          prefetch: 0
#          acknowledge-mode: manual
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.yhq.entity
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: true
#logging:
#  level:
#    com.yhq.dao: debug



